import './global.css'
import styles from "./layout.module.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { Header } from "@/components/header/Header";
import classNames from "classnames";
import { Footer } from '@/components/footer/Footer';

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classNames(inter.variable, styles.layout)}>
        <NextIntlClientProvider>
          <div className={styles.layoutWrapper}>
            <Header />
            <div className={styles.layoutWrapperContent}>
              {children}
            </div>
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
