version: '3.8'

services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.24.2
    ports:
      - "8083:8080"
      - "50053:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure
    env_file:
      - ./.env

  mongodb:
    image: mongo:6.0
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    env_file:
      - ./.env

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    pull_policy: always
    restart: unless-stopped
    env_file:
      - ./.env

  fastapi_app:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - weaviate
      - mongodb
      - ollama
    restart: on-failure
    env_file:
      - ./.env

  nextjs_chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - fastapi_app
    restart: on-failure
    env_file:
      - ./.env

  nextjs_cms:
    build:
      context: ./cms
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - fastapi_app
    restart: on-failure
    env_file:
      - ./.env

volumes:
  weaviate_data:
  mongo_data:
  ollama_data:
